---
- name: Pin Logstash version for apt
  copy:
    dest: /etc/apt/preferences.d/logstash
    content: |
      Package: logstash
      Pin: version 1:{{ logstash_version }}-*
      Pin-Priority: 1002
  notify:
    - Update Logstash

- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Disable Logstash service at startup
  systemd:
    name: logstash
    enabled: false
    state: stopped

- name: "Add current user to Logstash group"
  user:
    name: "{{ lookup('env','USER') }}"
    groups: "logstash"
    append: yes
