---
- environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ RVM_PATH }}:{{ JRUBY_PATH }}"
  name: "Check if JRuby is installed"
  shell: command -v jruby >/dev/null 2>&1 && echo "true" || echo "false"
  register: jruby_installed
  changed_when: False

- environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ RVM_PATH }}"
  name: "Install JRuby"
  shell: "rvm install {{ jruby_version }}"
  when: jruby_installed.stdout == "false"

- environment:
    PATH: "{{ lookup('env', 'PATH') }}:{{ RVM_PATH }}"
  name: "Configure RVM to use JRuby"
  shell: "rvm alias create default {{ jruby_version }}"
  when: jruby_installed.stdout == "false"
