---

####################
# RVM installation #
####################

- name: Include RVM installation part
  import_tasks: rvm.yml

######################
# JRuby installation #
######################

- name: Include JRuby installation part
  import_tasks: jruby.yml

########################
# Bundler installation #
########################

- name: Include Bundler installation part
  import_tasks: bundler.yml
